sudo: false

language: python

python:
  - 3.5

before_install:
  - "pip install -U pip"
  - "python setup.py install"

install:
  - pip install -r requirements.txt

script:

  - flake8 blackhole_data_gathering/
  - flake8 tests/  
  - coverage run -m unittest discover -s tests/ -v
  - coverage report -m

after_success:
  - codecov

notifications:
  email: never